# Generated by Django 3.0 on 2022-07-19 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220718_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_category',
            field=models.CharField(choices=[('WIZARDING CLOTHING', 'Wizarding Clothing'), ('BROOMS', 'Brooms'), ('WANDS', 'Wands'), ('MAGICAL BOOKS', 'Magical Books'), ('MAGICAL ITEMS', 'Magical Items'), ('MYTHICAL ITEMS', 'Mythical Items')], default='BROOMS', max_length=36),
        ),
        migrations.CreateModel(
            name='UsersWatchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_in_watchlist', models.ManyToManyField(blank=True, related_name='in_watchlist', to='auctions.Listing')),
                ('watchlist_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
